name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        # Thanks for taking the time to fill out this bug report!
        ### The following information will help us resolve your issue.
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Please describe your approach and, if possible, include a minimal working example we can use to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: traceback
    attributes:
      label: Traceback or logs
      description: Provide any additional information from an error stack of the associated stderr/stdout or console log.
  - type: dropdown
    id: operating_system
    attributes:
      label: Operating System
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: python_version
    attributes:
      label: Python Version
      options:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
    validations:
      required: true
  - type: dropdown
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: Do you agree to follow our [Code of Conduct](https://github.com/catalystneuro/tqdm_publisher/blob/main/.github/CODE_OF_CONDUCT.md)?
      options:
        - "Yes"
    validations:
      required: true
