name: Deploy tests

on:
  pull_request:

concurrency:  # Cancel previous workflows on the same pull request
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  assess-file-changes:
    uses: catalystneuro/tqdm_publisher/.github/workflows/assess-file-changes.yml@main

  detect-changelog-updates:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.SOURCE_CHANGED == 'true' }}
    name: Auto-detecting CHANGELOG.md updates
    runs-on: ubuntu-latest
    steps:
      - if:  ${{ needs.assess-file-changes.outputs.CHANGELOG_UPDATED == 'true' }}
        run: echo "CHANGELOG.md has been updated."
      - if:  ${{ needs.assess-file-changes.outputs.CHANGELOG_UPDATED == 'false' }}
        run: |
          echo "CHANGELOG.md has not been updated."
          0
  run-tests:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.SOURCE_CHANGED == 'true' }}
    uses: ./.github/workflows/testing.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  check-final-status:
    name: All tests passing
    if: always()

    needs:
    - run-tests

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the all jobs succeeded or at least one failed
      uses: re-actors/alls-green@release/v1
      with:
        allowed-skips: run-tests  # Sometimes only docs are adjusted
        jobs: ${{ toJSON(needs) }}
